package task1_JsonMapper;

public enum TokenTypes {
    JSON_COMMA,
    JSON_COLON,
    JSON_SQUARE_BRACKET_LEFT,
    JSON_SQUARE_BRACKET_RIGHT,
    JSON_CURLY_BRACKET_LEFT,
    JSON_CURLY_BRACKET_RIGHT,
}
